pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
      	sh 'echo Inject credentials'
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenNotBuilt: true, deleteDirs: true, disableDeferredWipeout: true, notFailBuild: true)
    }
  }
}
